---
kind: pipeline
type: ssh
name: build

server:
  host: 142.93.212.79
  user: root
  password: <Doctypehtml><br><786>n

trigger:
  branch:
    - master
  event:
    - push
    - pull_request

steps:
  - name: build-apk
    depends_on: [clone]
    commands:
      - cd ~
      - ls -l
      - cd ../..
      - ls
      - cd drone
      - ls -l
      - printenv
      # - export ANDROID_SDK_ROOT=$HOME/Android/Sdk
      # - echo $ANDROID_SDK_ROOT
      # - export PATH=$ANDROID_SDK_ROOT/cmdline-tools/tools/bin/:$PATH
      # - export PATH=$ANDROID_SDK_ROOT/emulator/:$PATH
      # - export PATH=$ANDROID_SDK_ROOT/platform-tools/:$PATH
      # - npm install
      # - cd android
      # - chmod +x gradlew
      # - ./gradlew assembleRelease

