---
kind: pipeline
type: ssh
name: build

server:
  host: 142.93.212.79
  user: root
  password: <Doctypehtml><br><786>n

trigger:
  branch:
    - master
  event:
    - push
    - pull_request

steps:
  - name: build-apk
    depends_on: [clone]
    commands:
      - cd android
      - chmod +x gradlew
      - npm install
      - ./gradlew assembleRelease

