---
kind: pipeline
type: ssh
name: build

server:
  host: 157.245.96.143
  user: root
  password: pakistan1234

trigger:
  branch:
    - master
  event:
    - push
    - pull_request

steps:
  - name: build-apk
    depends_on: [clone]
    commands:
      - export ANDROID_SDK_ROOT=/tmp/android/sdk
      - export PATH=$PATH:$ANDROID_SDK_ROOT/emulator
      - export PATH=$PATH:$ANDROID_SDK_ROOT/platform-tools
      - echo $ANDROID_SDK_ROOT
      - pwd
      - echo "Hi"
      - ls
      - npm install
      - ls
      - cd android
      - chmod +x gradlew
      - ./gradlew bundleRelease
      # - cd ~
      # - sudo apt-get -y install nano
      # - nano ~ /.profile
      # - source ~ /.profile
      # - cd ~ 
      # - ls -l
      # - cd ../..
      # - ls
      # - cd home
      # - ls -l
      # - printenv
      # - export ANDROID_SDK_ROOT=$HOME/Android/Sdk
      # - echo $ANDROID_SDK_ROOT
      # - ls -l
      # - export PATH=$ANDROID_SDK_ROOT/cmdline-tools/tools/bin/:$PATH
      # - export PATH=$ANDROID_SDK_ROOT/emulator/:$PATH
      # - export PATH=$ANDROID_SDK_ROOT/platform-tools/:$PATH
      

